"""empty message

Revision ID: f97fb7162ca6
Revises: 194a558753c0
Create Date: 2023-05-22 14:14:43.708615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97fb7162ca6'
down_revision = '194a558753c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stress_management_resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stress_management_resource', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
